### PR TITLE
feat(free-bsd): first-class support for FreeBSD

### LINKED ISSUE #49: FreeBSD support
I am using network-interface in [Aggligator](https://github.com/surban/aggligator/) and have received [a request](https://github.com/surban/aggligator/issues/6) to support FreeBSD. The only issue seems to be that it is currently unsupported by network-interface.

Thus FreeBSD support would be greatly appreciated.

### PR DESCRIPTION
**Pull request by surban**
Add support for FreeBSD and other BSDs.
Testing was only done using FreeBSD.

Fixes #49.

### CODE REVIEW

**Comment by surban** [comment]
The clippy failure seems to be unrelated to the performed changes.

**Comment by surban** [comment]
Anything I can do to help get this merged?

**Review by EstebanBorai — APPROVED** [review]
LGTM @surban! Thank you so much! I think I can help with clippy issues!

**Comment by EstebanBorai** [comment]
Hi @surban! Thanks for the support!
A release is already drafted here: https://crates.io/crates/network-interface/1.1.2

Please reach on any issues!

**Comment by cmspam** [comment]
Some issues compiling on aarch64:

```
error[E0308]: mismatched types
   --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/network-interface-1.1.2/src/target/unix/mod.rs:75:31
    |
75  |     let len = unsafe { strlen(data as *const i8) };
    |                        ------ ^^^^^^^^^^^^^^^^^ expected `*const u8`, found `*const i8`
    |                        |
    |                        arguments to this function are incorrect
    |
    = note: expected raw pointer `*const u8`
               found raw pointer `*const i8`
note: function defined here
   --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.153/src/unix/mod.rs:541:12
    |
541 |     pub fn strlen(cs: *const c_char) -> size_t;
    |            ^^^^^^

For more information about this error, try `rustc --explain E0308`.
error: could not compile `network-interface` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

**Comment by EstebanBorai** [comment]
> Some issues compiling on FreeBSD/aarch64:
> 
> 
> 
> ```
> 
> error[E0308]: mismatched types
> 
>    --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/network-interface-1.1.2/src/target/unix/mod.rs:75:31
> 
>     |
> 
> 75  |     let len = unsafe { strlen(data as *const i8) };
> 
>     |                        ------ ^^^^^^^^^^^^^^^^^ expected `*const u8`, found `*const i8`
> 
>     |                        |
> 
>     |                        arguments to this function are incorrect
> 
>     |
> 
>     = note: expected raw pointer `*const u8`
> 
>                found raw pointer `*const i8`
> 
> note: function defined here
> 
>    --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.153/src/unix/mod.rs:541:12
> 
>     |
> 
> 541 |     pub fn strlen(cs: *const c_char) -> size_t;
> 
>     |            ^^^^^^
> 
> 
> 
> For more information about this error, try `rustc --explain E0308`.
> 
> error: could not compile `network-interface` (lib) due to 1 previous error
> 
> warning: build failed, waiting for other jobs to finish...
> 
> ```

Thanks for sharing @cmspam! 
What do you think @surban? Does it happens to you as well?

**Comment by surban** [comment]
Not on x86_64. I don't have easy access to FreeBSD on aarch64. Do you have working CI support for that platform for your other project?

It might be enough to change `as *const i8` into `as *const _`.

**Comment by EstebanBorai** [comment]
> Not on x86_64. I don't have easy access to FreeBSD on aarch64. Do you have working CI support for that platform for your other projects?
> 
> 
> 
> It might be enough to change `as *const i8` into `as *const _`.

Gotcha! If the change works for you, and if you think that will fix the issue. Are you willing to open a PR?

**Comment by surban** [comment]
> Gotcha! If the change works for you, and if you think that will fix the issue. Are you willing to open a PR?

See #52

**Comment by EstebanBorai** [comment]
Thank you so much @surban!
@cmspam a new version has been released with @surban fix!

You can see it here: https://crates.io/crates/network-interface/1.1.3

Let us know any issues please!

**Comment by cmspam** [comment]
Many thanks to all involved! I won't have a chance to test on arm64 for a little bit, but I will let you know when I can.

**Pull request merged**
