### PR TITLE
feat: MAC address support for Linux

### PR DESCRIPTION
**Pull request by subtervisor**
Similar to the way macOS does it, though in a more idiomatic Rust way. Tested on my laptop.

### CODE REVIEW

**Comment by EstebanBorai** [comment]
Hi @subtervisor thanks so much for your contribution in this crate, I really appreciate it.

Running CI workflows I can see theres some clippy issues, can you address them please? So CI passes?

**Comment by subtervisor** [comment]
@EstebanBorai that failure is preexisting from the macOS code that you added and I can't test it (as I don't have a macOS host), so I wasn't sure whether or not to fix it, especially since the code is technically unrelated to this change. I'll make the change though.

**Comment by EstebanBorai** [comment]
> @EstebanBorai that failure is preexisting from the macOS code that you added and I can't test it (as I don't have a macOS host), so I wasn't sure whether or not to fix it, especially since the code is technically unrelated to this change. I'll make the change though.

Oh! Just noticed about that! Thought it was related to most recent `cargo` versions!
Thanks for taking the time!

**Review by EstebanBorai — APPROVED** [review]
Thanks so much @subtervisor!

**Pull request merged**
