### PR TITLE
Fix/windows memory leaks

### PR DESCRIPTION
**Pull request by scanban**
Removed 2 memory leaks in windows related code, added FFI output
buffer management wit RAII. Removed not needed memory allocation(s)

PS. ohh, looks like @njeisecke already added same ;) Feel free to drop mine if not needed

### CODE REVIEW

**Comment by njeisecke** [comment]
That's funny. I think your generic FFIAlloc<T> is better. However I prefer my alloc retry logic and error handling, feels more like proper rust to me ;-)

**Comment by njeisecke** [comment]
I think 0b2b6b76fd9b2a9ff35f764347109ad64f636d4a contains stuff not actually related to the leak.

**Comment by scanban** [comment]
> I think [0b2b6b7](https://github.com/EstebanBorai/network-interface/commit/0b2b6b76fd9b2a9ff35f764347109ad64f636d4a) contains changes not actually related to the leak (probably for the better, but this should be a separate commit).

it is, plus some simplifications/style of the code. Next should be creating of network interfaces based on interface index
with multiple addresses to be on par with the Linux results.

**Comment by EstebanBorai** [comment]
Hi @scanban! I can see you are also participanting in the PR opened by @njeisecke. Would you like to focus in such PR? So we all participate in the same effort?

**Comment by scanban** [comment]
> Hi @scanban! I can see you are also participanting in the PR opened by @njeisecke. Would you like to focus in such PR? So we all participate in the same effort?

Hello @EstebanBorai, yea sure. I think that @njeisecke could get some bits from my changes if he decide to do that.
And my PR then could be dropped.

**Comment by njeisecke** [comment]
Yeah, I would use the generic RAII wrapper and restore the retry counter. @scanban, would you then do a follow-up with your other changes?

**Comment by scanban** [comment]
> Yeah, I would use the generic RAII wrapper and restore the retry counter. @scanban, would you then do a follow-up with your other changes?

yea, sure

**Pull request closed without merging**
